<a href="https://colab.research.google.com/github/Aje-dotcom/DeepTech-/blob/master/Ekene_Ajemba_Assignment1_Week4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Applied Learning Assignments 1:

Kindly find attached tables (here) as provided to answer the following questions:
1. Convert this dataset into 1NF: Remove duplicate values and ensure atomicity.
2. Transform into 2NF: Eliminate partial dependencies by creating separate tables.
3. Achieve 3NF: Remove transitive dependencies and ensure all non-key attributes depend only on the primary key.
4. Transform the data by updating employee salaries with a 10% increase for employees in the IT department.

### 1. Load the Dataset
First, I'll upload and read the Excel file data.

In [1]:

import pandas as pd
import sqlite3
from google.colab import files

uploaded = files.upload()

file_name = '/content/drive/MyDrive/DeepTech_Ready_Cohort3 /Week 4/SQL for Data Analysis and Automation Assignment 1_31bc6869c4f7e83f522b6db282bcc32a.xlsx'
df = pd.read_excel(file_name)

print(df.head())

Saving SQL for Data Analysis and Automation Assignment 1_31bc6869c4f7e83f522b6db282bcc32a.xlsx to SQL for Data Analysis and Automation Assignment 1_31bc6869c4f7e83f522b6db282bcc32a (1).xlsx
   emp_id        emp_name   department  salary department_location  manager_id
0     101      Umar Adamu           HR   50000              Lokoja         201
1     102        Jane Abu           IT   60000         Cross River         202
2     103    Caroline Agu      Finance   55000              Sokoto         203
3     104      Shehu Umar    Logistics   48000             Zamfara         204
4     105  Mohammed Bello  Procurement   53000              Jigawa         205

In [2]:
conn = sqlite3.connect('assignment.db')

df.to_sql('EmployeeData', conn, if_exists='replace', index=False)

query = "SELECT * FROM EmployeeData"
display(pd.read_sql(query, conn).head())

   emp_id        emp_name   department  salary department_location  manager_id
0     101      Umar Adamu           HR   50000              Lokoja         201
1     102        Jane Abu           IT   60000         Cross River         202
2     103    Caroline Agu      Finance   55000              Sokoto         203
3     104      Shehu Umar    Logistics   48000             Zamfara         204
4     105  Mohammed Bello  Procurement   53000              Jigawa         205

### 2. Convert to 1NF (First Normal Form)
Requirement: Ensure atomicity (one value per cell) and remove duplicates.
In my data,<b><p>Step 1: Converting the dataset into 1NF</b><br>
To convert the dataset into<b> First Normal Form, </b></br>I ensured that:
* each column contains only <b>atomic values<br></b>
* there are no repeating groups<br>
* duplicate rows are removed<br><p>
The original dataset already had atomic fields such as emp_id, emp_name, department, salary, department_location, and manager_id, so the main adjustment was removing duplicate rows.
The resulting <b>1NF table is:</b>

In [6]:
query_1nf = """
CREATE TABLE Employee_1NF AS
SELECT DISTINCT
    emp_id,
    emp_name,
    department,
    salary,
    department_location,
    manager_id
FROM EmployeeData;
"""
conn.execute("DROP TABLE IF EXISTS Employee_1NF")
conn.execute(query_1nf)

display(pd.read_sql("SELECT * FROM Employee_1NF", conn))

   emp_id        emp_name   department  salary department_location  manager_id
0     101      Umar Adamu           HR   50000              Lokoja         201
1     102        Jane Abu           IT   60000         Cross River         202
2     103    Caroline Agu      Finance   55000              Sokoto         203
3     104      Shehu Umar    Logistics   48000             Zamfara         204
4     105  Mohammed Bello  Procurement   53000              Jigawa         205
5     106       Frank Ewu           IT   62000               Delta         202

This table satisfies 1NF because every attribute contains only a single value and there are no duplicate records.

### Transforming the dataset into 2NF
To achieve Second Normal Form, I removed partial dependency by separating employee details from department-related details.

The reason for this is that department_location and manager_id depend on the department, not directly on the employee.

So the dataset was decomposed into the following tables:

In [7]:
conn.execute("DROP TABLE IF EXISTS Employees_2NF")
conn.execute("DROP TABLE IF EXISTS Departments_2NF")

query_employees_2nf = """
CREATE TABLE Employees_2NF AS
SELECT DISTINCT
    emp_id,
    emp_name,
    department,
    salary
FROM Employee_1NF;
"""

query_departments_2nf = """
CREATE TABLE Departments_2NF AS
SELECT DISTINCT
    department,
    department_location,
    manager_id
FROM Employee_1NF;
"""

conn.execute(query_employees_2nf)
conn.execute(query_departments_2nf)

print("Employees_2NF")
display(pd.read_sql("SELECT * FROM Employees_2NF", conn))

print("Departments_2NF")
display(pd.read_sql("SELECT * FROM Departments_2NF", conn))

Employees_2NF

   emp_id        emp_name   department  salary
0     101      Umar Adamu           HR   50000
1     102        Jane Abu           IT   60000
2     103    Caroline Agu      Finance   55000
3     104      Shehu Umar    Logistics   48000
4     105  Mohammed Bello  Procurement   53000
5     106       Frank Ewu           IT   62000

Departments_2NF

    department department_location  manager_id
0           HR              Lokoja         201
1           IT         Cross River         202
2      Finance              Sokoto         203
3    Logistics             Zamfara         204
4  Procurement              Jigawa         205
5           IT               Delta         202

This step separates employee details from department details.

In [9]:
conn.execute("DROP TABLE IF EXISTS Employees_3NF")
conn.execute("DROP TABLE IF EXISTS Departments_3NF")
conn.execute("DROP TABLE IF EXISTS Managers_3NF")

query_employees_3nf = """
CREATE TABLE Employees_3NF AS
SELECT DISTINCT
    emp_id,
    emp_name,
    department,
    salary
FROM Employee_1NF;
"""

query_departments_3nf = """
CREATE TABLE Departments_3NF AS
SELECT DISTINCT
    department,
    department_location,
    manager_id
FROM Employee_1NF;
"""

query_managers_3nf = """
CREATE TABLE Managers_3NF AS
SELECT DISTINCT
    manager_id
FROM Employee_1NF;
"""

conn.execute(query_employees_3nf)
conn.execute(query_departments_3nf)
conn.execute(query_managers_3nf)

print("Employees_3NF")
display(pd.read_sql("SELECT * FROM Employees_3NF", conn))

print("Departments_3NF")
display(pd.read_sql("SELECT * FROM Departments_3NF", conn))

print("Managers_3NF")
display(pd.read_sql("SELECT * FROM Managers_3NF", conn))

Employees_3NF

   emp_id        emp_name   department  salary
0     101      Umar Adamu           HR   50000
1     102        Jane Abu           IT   60000
2     103    Caroline Agu      Finance   55000
3     104      Shehu Umar    Logistics   48000
4     105  Mohammed Bello  Procurement   53000
5     106       Frank Ewu           IT   62000

Departments_3NF

    department department_location  manager_id
0           HR              Lokoja         201
1           IT         Cross River         202
2      Finance              Sokoto         203
3    Logistics             Zamfara         204
4  Procurement              Jigawa         205
5           IT               Delta         202

Managers_3NF

   manager_id
0         201
1         202
2         203
3         204
4         205

This *3NF* step removes transitive dependency by separating managers into their own table

Update salaries for IT staff by 10%

In [10]:

update_query = """
UPDATE Employees_3NF
SET salary = salary * 1.10
WHERE department = 'IT';
"""

conn.execute(update_query)
conn.commit()

display(pd.read_sql("SELECT * FROM Employees_3NF WHERE department = 'IT'", conn))

   emp_id   emp_name department  salary
0     102   Jane Abu         IT   66000
1     106  Frank Ewu         IT   68200

Save the final tables to Excel, and helps you download the results from Collab.

In [11]:

employees_1nf = pd.read_sql("SELECT * FROM Employee_1NF", conn)
display("\nEmployees 1NF (head):\n", employees_1nf.head())
employees_3nf = pd.read_sql("SELECT * FROM Employees_3NF", conn)
display("\nEmployees 3NF (head):\n", employees_3nf.head())
departments_3nf = pd.read_sql("SELECT * FROM Departments_3NF", conn)
display("\nDepartments 3NF (head):\n", departments_3nf.head())
managers_3nf = pd.read_sql("SELECT * FROM Managers_3NF", conn)
display("\nManagers 3NF (head):\n", managers_3nf.head())

with pd.ExcelWriter('normalized_employee_tables_colab.xlsx', engine='openpyxl') as writer:
    employees_1nf.to_excel(writer, sheet_name='1NF', index=False)
    employees_3nf.to_excel(writer, sheet_name='Employees_3NF', index=False)
    departments_3nf.to_excel(writer, sheet_name='Departments_3NF', index=False)
    managers_3nf.to_excel(writer, sheet_name='Managers_3NF', index=False)

files.download('normalized_employee_tables_colab.xlsx')

Employees 1NF (head):
    emp_id        emp_name   department  salary department_location  manager_id
0     101      Umar Adamu           HR   50000              Lokoja         201
1     102        Jane Abu           IT   60000         Cross River         202
2     103    Caroline Agu      Finance   55000              Sokoto         203
3     104      Shehu Umar    Logistics   48000             Zamfara         204
4     105  Mohammed Bello  Procurement   53000              Jigawa         205

Employees 3NF (head):
    emp_id        emp_name   department  salary
0     101      Umar Adamu           HR   50000
1     102        Jane Abu           IT   66000
2     103    Caroline Agu      Finance   55000
3     104      Shehu Umar    Logistics   48000
4     105  Mohammed Bello  Procurement   53000

Departments 3NF (head):
     department department_location  manager_id
0           HR              Lokoja         201
1           IT         Cross River         202
2      Finance              Sokoto         203
3    Logistics             Zamfara         204
4  Procurement              Jigawa         205

Managers 3NF (head):
    manager_id
0         201
1         202
2         203
3         204
4         205

In [12]:
display(employees_3nf)

   emp_id        emp_name   department  salary
0     101      Umar Adamu           HR   50000
1     102        Jane Abu           IT   66000
2     103    Caroline Agu      Finance   55000
3     104      Shehu Umar    Logistics   48000
4     105  Mohammed Bello  Procurement   53000
5     106       Frank Ewu           IT   68200

In [13]:
display(departments_3nf)

    department department_location  manager_id
0           HR              Lokoja         201
1           IT         Cross River         202
2      Finance              Sokoto         203
3    Logistics             Zamfara         204
4  Procurement              Jigawa         205
5           IT               Delta         202

### Title
SQL for Data Analysis and Automation Assignment 1

### Introduction
The dataset was loaded into Google Colab, stored in SQLite, and normalized from 1NF to 3NF using SQL queries.

### Method

* Duplicate rows were removed in 1NF
* Department-related attributes were separated in 2NF
* Manager information was isolated in 3NF
* Salaries of IT staff were updated using an UPDATE statement
### Result
Show the output tables from each SQL step.

### Conclusion
State that the dataset was successfully normalized and the IT salary increase was correctly applied.