<a href="https://colab.research.google.com/github/Aje-dotcom/DeepTech-/blob/master/Ekene_Ajemba_Assignment1_Week4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Applied Learning Assignments 1:

Kindly find attached tables (here) as provided to answer the following questions:
1. Convert this dataset into 1NF: Remove duplicate values and ensure atomicity.
2. Transform into 2NF: Eliminate partial dependencies by creating separate tables.
3. Achieve 3NF: Remove transitive dependencies and ensure all non-key attributes depend only on the primary key.
4. Transform the data by updating employee salaries with a 10% increase for employees in the IT department.

### 1. Load the Dataset
First, I'll upload and read the Excel file data.

In [ ]:

import pandas as pd
import sqlite3
from google.colab import files

uploaded = files.upload()

file_name = '/content/drive/MyDrive/DeepTech_Ready_Cohort3 /Week 4/SQL for Data Analysis and Automation Assignment 1_31bc6869c4f7e83f522b6db282bcc32a.xlsx'
df = pd.read_excel(file_name)

print(df.head())

Saving SQL for Data Analysis and Automation Assignment 1_31bc6869c4f7e83f522b6db282bcc32a.xlsx to SQL for Data Analysis and Automation Assignment 1_31bc6869c4f7e83f522b6db282bcc32a (1).xlsx
   emp_id        emp_name   department  salary department_location  manager_id
0     101      Umar Adamu           HR   50000              Lokoja         201
1     102        Jane Abu           IT   60000         Cross River         202
2     103    Caroline Agu      Finance   55000              Sokoto         203
3     104      Shehu Umar    Logistics   48000             Zamfara         204
4     105  Mohammed Bello  Procurement   53000              Jigawa         205

In [ ]:
conn = sqlite3.connect('assignment.db')

df.to_sql('EmployeeData', conn, if_exists='replace', index=False)

query = "SELECT * FROM EmployeeData"
display(pd.read_sql(query, conn).head())

   emp_id        emp_name   department  salary department_location  manager_id
0     101      Umar Adamu           HR   50000              Lokoja         201
1     102        Jane Abu           IT   60000         Cross River         202
2     103    Caroline Agu      Finance   55000              Sokoto         203
3     104      Shehu Umar    Logistics   48000             Zamfara         204
4     105  Mohammed Bello  Procurement   53000              Jigawa         205

### 2. Convert to 1NF (First Normal Form)
Requirement: Ensure atomicity (one value per cell) and remove duplicates.
In my data,<b><p>Step 1: Converting the dataset into 1NF</b><br>
To convert the dataset into<b> First Normal Form, </b></br>I ensured that:
* each column contains only <b>atomic values<br></b>
* there are no repeating groups<br>
* duplicate rows are removed<br><p>
The original dataset already had atomic fields such as emp_id, emp_name, department, salary, department_location, and manager_id, so the main adjustment was removing duplicate rows.
The resulting <b>1NF table is:</b>

In [ ]:
query_1nf = """
CREATE TABLE Employee_1NF AS
SELECT DISTINCT
    emp_id,
    emp_name,
    department,
    salary,
    department_location,
    manager_id
FROM EmployeeData;
"""
conn.execute("DROP TABLE IF EXISTS Employee_1NF")
conn.execute(query_1nf)

display(pd.read_sql("SELECT * FROM Employee_1NF", conn))

   emp_id        emp_name   department  salary department_location  manager_id
0     101      Umar Adamu           HR   50000              Lokoja         201
1     102        Jane Abu           IT   60000         Cross River         202
2     103    Caroline Agu      Finance   55000              Sokoto         203
3     104      Shehu Umar    Logistics   48000             Zamfara         204
4     105  Mohammed Bello  Procurement   53000              Jigawa         205
5     106       Frank Ewu           IT   62000               Delta         202

This table satisfies 1NF because every attribute contains only a single value and there are no duplicate records.

### Transforming the dataset into 2NF
To achieve Second Normal Form, I removed partial dependency by separating employee details from department-related details.

The reason for this is that department_location and manager_id depend on the department, not directly on the employee.

So the dataset was decomposed into the following tables:

In [ ]:
conn.execute("DROP TABLE IF EXISTS Employees_2NF")
conn.execute("DROP TABLE IF EXISTS Departments_2NF")

query_employees_2nf = """
CREATE TABLE Employees_2NF AS
SELECT DISTINCT
    emp_id,
    emp_name,
    department,
    salary
FROM Employee_1NF;
"""

query_departments_2nf = """
CREATE TABLE Departments_2NF AS
SELECT DISTINCT
    department,
    department_location,
    manager_id
FROM Employee_1NF;
"""

conn.execute(query_employees_2nf)
conn.execute(query_departments_2nf)

print("Employees_2NF")
display(pd.read_sql("SELECT * FROM Employees_2NF", conn))

print("Departments_2NF")
display(pd.read_sql("SELECT * FROM Departments_2NF", conn))

Employees_2NF

   emp_id        emp_name   department  salary
0     101      Umar Adamu           HR   50000
1     102        Jane Abu           IT   60000
2     103    Caroline Agu      Finance   55000
3     104      Shehu Umar    Logistics   48000
4     105  Mohammed Bello  Procurement   53000
5     106       Frank Ewu           IT   62000

Departments_2NF

    department department_location  manager_id
0           HR              Lokoja         201
1           IT         Cross River         202
2      Finance              Sokoto         203
3    Logistics             Zamfara         204
4  Procurement              Jigawa         205
5           IT               Delta         202

This step separates employee details from department details.

In [ ]:
conn.execute("DROP TABLE IF EXISTS Employees_3NF")
conn.execute("DROP TABLE IF EXISTS Departments_3NF")
conn.execute("DROP TABLE IF EXISTS Managers_3NF")

query_employees_3nf = """
CREATE TABLE Employees_3NF AS
SELECT DISTINCT
    emp_id,
    emp_name,
    department,
    salary
FROM Employee_1NF;
"""

query_departments_3nf = """
CREATE TABLE Departments_3NF AS
SELECT DISTINCT
    department,
    department_location,
    manager_id
FROM Employee_1NF;
"""

query_managers_3nf = """
CREATE TABLE Managers_3NF AS
SELECT DISTINCT
    manager_id
FROM Employee_1NF;
"""

conn.execute(query_employees_3nf)
conn.execute(query_departments_3nf)
conn.execute(query_managers_3nf)

print("Employees_3NF")
display(pd.read_sql("SELECT * FROM Employees_3NF", conn))

print("Departments_3NF")
display(pd.read_sql("SELECT * FROM Departments_3NF", conn))

print("Managers_3NF")
display(pd.read_sql("SELECT * FROM Managers_3NF", conn))

Employees_3NF

   emp_id        emp_name   department  salary
0     101      Umar Adamu           HR   50000
1     102        Jane Abu           IT   60000
2     103    Caroline Agu      Finance   55000
3     104      Shehu Umar    Logistics   48000
4     105  Mohammed Bello  Procurement   53000
5     106       Frank Ewu           IT   62000

Departments_3NF

    department department_location  manager_id
0           HR              Lokoja         201
1           IT         Cross River         202
2      Finance              Sokoto         203
3    Logistics             Zamfara         204
4  Procurement              Jigawa         205
5           IT               Delta         202

Managers_3NF

   manager_id
0         201
1         202
2         203
3         204
4         205

This *3NF* step removes transitive dependency by separating managers into their own table

Update salaries for IT staff by 10%

In [ ]:

update_query = """
UPDATE Employees_3NF
SET salary = salary * 1.10
WHERE department = 'IT';
"""

conn.execute(update_query)
conn.commit()

display(pd.read_sql("SELECT * FROM Employees_3NF WHERE department = 'IT'", conn))

   emp_id   emp_name department  salary
0     102   Jane Abu         IT   66000
1     106  Frank Ewu         IT   68200

Save the final tables to Excel, and helps you download the results from Collab.

In [ ]:

employees_1nf = pd.read_sql("SELECT * FROM Employee_1NF", conn)
display("\nEmployees 1NF (head):\n", employees_1nf.head())
employees_3nf = pd.read_sql("SELECT * FROM Employees_3NF", conn)
display("\nEmployees 3NF (head):\n", employees_3nf.head())
departments_3nf = pd.read_sql("SELECT * FROM Departments_3NF", conn)
display("\nDepartments 3NF (head):\n", departments_3nf.head())
managers_3nf = pd.read_sql("SELECT * FROM Managers_3NF", conn)
display("\nManagers 3NF (head):\n", managers_3nf.head())

with pd.ExcelWriter('normalized_employee_tables_colab.xlsx', engine='openpyxl') as writer:
    employees_1nf.to_excel(writer, sheet_name='1NF', index=False)
    employees_3nf.to_excel(writer, sheet_name='Employees_3NF', index=False)
    departments_3nf.to_excel(writer, sheet_name='Departments_3NF', index=False)
    managers_3nf.to_excel(writer, sheet_name='Managers_3NF', index=False)

files.download('normalized_employee_tables_colab.xlsx')

Employees 1NF (head):
    emp_id        emp_name   department  salary department_location  manager_id
0     101      Umar Adamu           HR   50000              Lokoja         201
1     102        Jane Abu           IT   60000         Cross River         202
2     103    Caroline Agu      Finance   55000              Sokoto         203
3     104      Shehu Umar    Logistics   48000             Zamfara         204
4     105  Mohammed Bello  Procurement   53000              Jigawa         205

Employees 3NF (head):
    emp_id        emp_name   department  salary
0     101      Umar Adamu           HR   50000
1     102        Jane Abu           IT   66000
2     103    Caroline Agu      Finance   55000
3     104      Shehu Umar    Logistics   48000
4     105  Mohammed Bello  Procurement   53000

Departments 3NF (head):
     department department_location  manager_id
0           HR              Lokoja         201
1           IT         Cross River         202
2      Finance              Sokoto         203
3    Logistics             Zamfara         204
4  Procurement              Jigawa         205

Managers 3NF (head):
    manager_id
0         201
1         202
2         203
3         204
4         205

In [ ]:
display(employees_3nf)

   emp_id        emp_name   department  salary
0     101      Umar Adamu           HR   50000
1     102        Jane Abu           IT   66000
2     103    Caroline Agu      Finance   55000
3     104      Shehu Umar    Logistics   48000
4     105  Mohammed Bello  Procurement   53000
5     106       Frank Ewu           IT   68200

In [ ]:
display(departments_3nf)

    department department_location  manager_id
0           HR              Lokoja         201
1           IT         Cross River         202
2      Finance              Sokoto         203
3    Logistics             Zamfara         204
4  Procurement              Jigawa         205
5           IT               Delta         202

### Title
SQL for Data Analysis and Automation Assignment 1

### Introduction
The dataset was loaded into Google Colab, stored in SQLite, and normalized from 1NF to 3NF using SQL queries.

### Method

* Duplicate rows were removed in 1NF
* Department-related attributes were separated in 2NF
* Manager information was isolated in 3NF
* Salaries of IT staff were updated using an UPDATE statement
### Result
Show the output tables from each SQL step.

### Conclusion
State that the dataset was successfully normalized and the IT salary increase was correctly applied.

## Applied Learning Assignments 2:

Kindly find attached tables to answer the following questions:

Explain the importance of data warehousing in decision-making. Write an SQL View that retrieves customers who have spent more than 300,000 Naira in total purchases. Create a Materialized View that summarizes total sales per month. Write a stored procedure called update_product_price that increases the price of Phones by 10%.


## 1. Importance of data warehousing in decision-making<p>
A <b>data warehouse</b> is important in decision-making because it brings data from different operational systems into one central, organized repository for analysis. Instead of managers looking at scattered data from sales, customers, products, and finance separately, the warehouse gives them a single version of the truth.

✅It improves decision-making in a few key ways:

✅Better reporting

A data warehouse stores historical and current data in a structured format, making it easier to generate reports and dashboards.

✅Faster analysis

Since the data is already cleaned, integrated, and optimized for querying, decision-makers can analyze trends quickly without slowing down operational systems.

✅Historical insights

Operational databases usually focus on current transactions, but a warehouse keeps historical data, which helps management study patterns over time such as monthly sales growth, customer behavior, and seasonal demand.

✅Improved data quality

Data warehousing involves cleaning and standardizing data, reducing inconsistencies and making reports more reliable.

✅Supports strategic decisions

Executives can use warehouse data to decide on pricing, market expansion, customer targeting, stock planning, and product performance.

In short, <b>data warehousing</b> helps organizations make more accurate, timely, and strategic business decisions by transforming raw data into useful information.

In [ ]:
from google.colab import files

uploaded = files.upload()

fileName = '/content/drive/MyDrive/DeepTech_Ready_Cohort3 /Week 4/SQL for Data Analysis and Automation Assignment 1_31bc6869c4f7e83f522b6db282bcc32a.xlsx'
df = pd.read_excel(fileName)

print(df.head())

Saving SQL for Data Analysis and Automation Assignment 2_4f6e3f50d6f57990c34de1ac64295cbd (1).xlsx to SQL for Data Analysis and Automation Assignment 2_4f6e3f50d6f57990c34de1ac64295cbd (1) (1).xlsx
   emp_id        emp_name   department  salary department_location  manager_id
0     101      Umar Adamu           HR   50000              Lokoja         201
1     102        Jane Abu           IT   60000         Cross River         202
2     103    Caroline Agu      Finance   55000              Sokoto         203
3     104      Shehu Umar    Logistics   48000             Zamfara         204
4     105  Mohammed Bello  Procurement   53000              Jigawa         205

### 2. SQL View for customers who have spent more than 300,000 Naira
Assuming there is a transaction table called `sales` with:

* customer_id
* amount

and a customer table called _customers_ with:

* customer_id
* name

the SQL View would be:

In [ ]:
sql_view_query = """
CREATE VIEW high_value_customers AS
SELECT
    c.customer_id,
    c.name,
    SUM(s.amount) AS total_spent
FROM customers c
JOIN sales s
    ON c.customer_id = s.customer_id
GROUP BY c.customer_id, c.name
HAVING SUM(s.amount) > 300000;
"""

conn.execute(sql_view_query)

This view returns only customers whose total purchases exceed 300,000 Naira.

### 3. Materialized View for total sales per month
A materialized view stores the result physically, so it is useful for repeated reporting and faster aggregation.

Assuming:

* sales.purchase_date
* sales.amount

In [ ]:
sql_mv_query = """
CREATE VIEW monthly_sales_summary AS
SELECT
    strftime('%Y-%m', purchase_date) AS sales_month,
    SUM(amount) AS total_sales
FROM sales
GROUP BY strftime('%Y-%m', purchase_date);
"""

conn.execute(sql_mv_query)
conn.commit()

In [ ]:
# The 'monthly_sales_summary' is now a standard view in SQLite.
# Standard views are dynamic and automatically reflect the latest data.
# Therefore, a 'REFRESH' command is not needed and not supported.

In [ ]:
sql_query_sales_summary = """
SELECT
    strftime('%Y-%m', purchase_date) AS sales_month,
    SUM(amount) AS total_sales
FROM sales
GROUP BY strftime('%Y-%m', purchase_date);
"""

# Assuming a 'sales' table and 'conn' object exist as previously established.
# This is a SELECT query, so you'd typically fetch results.
# For demonstration, let's just execute it and print some output if it were to run.
# conn.execute(sql_query_sales_summary)
# conn.commit()

# To actually get results from a SELECT statement, you'd use pd.read_sql:
# try:
#     result_df = pd.read_sql(sql_query_sales_summary, conn)
#     display(result_df)
# except Exception as e:
#     print(f"Error executing query: {e}")

print("SQL query for monthly sales summary is defined. If you want to execute it and display results, uncomment the relevant lines.")

SQL query for monthly sales summary is defined. If you want to execute it and display results, uncomment the relevant lines.

Some database does not support DATE_TRUNC, the syntax may differ. in (sqlíte) MySQL, you would usually simulate monthly grouping with DATE_FORMAT() but true materialized views are not natively supported in MySQL.

### 4. Stored procedure
update_product_price to increase the price of Phones by 10%
Assuming the products table is called products and includes:

* product_name
* price

In [ ]:
# SQLite does not support stored procedures or the `CALL` syntax.
# The actual update is performed by directly executing the UPDATE statement.
# Refer to cell `sTW0VHv70byr` for the correct implementation.
# For example, to apply the update here, you would use:
# conn.execute("UPDATE products SET price = price * 1.10 WHERE product_name = 'Phone';")
# conn.commit()

### Fetching Product Data

To demonstrate fetching product data, I'll first create a simple `products` table in the SQLite database, as it was not part of the original dataset loaded. Then I will query it using pandas.

In [ ]:
conn.execute("DROP TABLE IF EXISTS products;")
conn.execute("""
CREATE TABLE products (
    product_id INTEGER PRIMARY KEY,
    product_name TEXT NOT NULL,
    price REAL NOT NULL
);
""")

conn.execute("""
INSERT INTO products (product_id, product_name, price) VALUES
    (1, 'Laptop', 1200.00),
    (2, 'Phone', 800.00),
    (3, 'Tablet', 450.00),
    (4, 'Monitor', 300.00);
""")
conn.commit()

print("Dummy 'products' table created and populated.")

Dummy 'products' table created and populated.

In [ ]:
products_df = pd.read_sql("SELECT * FROM products", conn)
display(products_df)

   product_id product_name   price
0           1       Laptop  1200.0
1           2        Phone   800.0
2           3       Tablet   450.0
3           4      Monitor   300.0

In [ ]:
# SQLite does not support stored procedures or DELIMITER syntax.
# To achieve the desired update, we can directly execute the UPDATE statement.

sql_update_price = """
UPDATE products
SET price = price * 1.10
WHERE product_name = 'Phone';
"""

conn.execute(sql_update_price)
conn.commit()

print("Price of 'Phone' increased by 10%.")

# Optional: Verify the update
# products_df_updated = pd.read_sql("SELECT * FROM products WHERE product_name = 'Phone'", conn)
# display(products_df_updated)

Price of 'Phone' increased by 10%.

In [ ]:
products_df_updated = pd.read_sql("SELECT * FROM products", conn)
display(products_df_updated)

   product_id product_name   price
0           1       Laptop  1200.0
1           2        Phone   880.0
2           3       Tablet   450.0
3           4      Monitor   300.0

### Final note
Because the uploaded sheet preview mainly showed the `Customer Table` and `Products Table`, I had to make a practical assumption that a sales table is for purchases. That assumption is necessary for the view and materialized view questions

_______________________________


Applied Learning Assignments 3:
Kindly find attached tables (find table here) to answer the following questions:
Write a SQL script to create the tables with constraints.Write a SQL transaction to handle an order purchase. If the product is out of stock, the transaction should rollback.Partition the Orders table based on OrderDate using RANGE partitioning (e.g., orders before 2023 go to one partition, and 2023+ orders go to another).Explain how indexing improved query performance.

In [13]:
get_ipython().system('pip install sqlite3')
import sqlite3
from google.colab import files
import pandas as pd

uploaded = files.upload()

file_data = '/content/drive/MyDrive/DeepTech_Ready_Cohort3 /Week 4/SQL for Data Analysis and Automation Assignment 1_31bc6869c4f7e83f522b6db282bcc32a.xlsx'
df = pd.read_excel(file_data)

display(df.head())

ERROR: Could not find a version that satisfies the requirement sqlite3 (from versions: none)
ERROR: No matching distribution found for sqlite3

Saving SQL for Data Analysis and Automation Assignment 3_13c063138ee73eea64d20aa3861fa8bd.xlsx to SQL for Data Analysis and Automation Assignment 3_13c063138ee73eea64d20aa3861fa8bd (4).xlsx

   emp_id        emp_name   department  salary department_location  manager_id
0     101      Umar Adamu           HR   50000              Lokoja         201
1     102        Jane Abu           IT   60000         Cross River         202
2     103    Caroline Agu      Finance   55000              Sokoto         203
3     104      Shehu Umar    Logistics   48000             Zamfara         204
4     105  Mohammed Bello  Procurement   53000              Jigawa         205

## Applied Learning Assignment 3
#### File Used
SQL for Data Analysis and Automation Assignment 3_13c063138ee73eea64d20aa3861fa8bd.xlsx

#### Overview
The attached Excel file contains the structure of four related tables used in an order management system:

✅ Customers<br>
✅ Products<br>
✅ Orders<br>
✅ OrderDetails<br>

The task requires:

creating the tables with constraints, writing a transaction to process an order purchase with rollback if stock is unavailable,
partitioning the Orders table using `RANGE` partitioning on OrderDate,
and explaining how indexing improves performance.

##1. SQL script to create the tables with constraints

In [16]:
import sqlite3

# Establish connection to an SQLite database file for Assignment 3
conn = sqlite3.connect('ordermanagement_assignment3.db')

# These commands are for other SQL dialects (like MySQL) and are not needed for SQLite.
# CREATE DATABASE OrderManagement;
# USE OrderManagement;

# Drop tables if they exist to allow re-running the cell
conn.execute("DROP TABLE IF EXISTS OrderDetails;")
conn.execute("DROP TABLE IF EXISTS Orders;")
conn.execute("DROP TABLE IF EXISTS Products;")
conn.execute("DROP TABLE IF EXISTS Customers;")

conn.execute("""
CREATE TABLE Customers (
    CustomerID INTEGER PRIMARY KEY AUTOINCREMENT,
    FirstName TEXT NOT NULL,
    LastName TEXT NOT NULL,
    Email TEXT UNIQUE NOT NULL,
    Phone TEXT
    -- SQLite does not natively support REGEXP in CHECK constraints without custom functions.
    -- CONSTRAINT chk_phone
    --     CHECK (Phone REGEXP '^[0-9]{10,15}$')
);
""")

conn.execute("""
CREATE TABLE Products (
    ProductID INTEGER PRIMARY KEY AUTOINCREMENT,
    ProductName TEXT NOT NULL,
    Price DECIMAL(10,2),
    StockQuantity INT,
    CONSTRAINT chk_price
        CHECK (Price > 0),
    CONSTRAINT chk_stock
        CHECK (StockQuantity >= 0)
);
""")

conn.execute("""
CREATE TABLE Orders (
    OrderID INTEGER PRIMARY KEY AUTOINCREMENT,
    CustomerID INT,
    OrderDate DATE NOT NULL,
    TotalAmount DECIMAL(10,2),
    CONSTRAINT chk_totalamount
        CHECK (TotalAmount > 0),
    CONSTRAINT fk_orders_customer
        FOREIGN KEY (CustomerID) REFERENCES Customers(CustomerID)
);
""")

conn.execute("""
CREATE TABLE OrderDetails (
    OrderDetailID INTEGER PRIMARY KEY AUTOINCREMENT,
    OrderID INT,
    ProductID INT,
    Quantity INT,
    Subtotal DECIMAL(10,2),
    CONSTRAINT chk_quantity
        CHECK (Quantity > 0),
    CONSTRAINT chk_subtotal
        CHECK (Subtotal > 0),
    CONSTRAINT fk_orderdetails_order
        FOREIGN KEY (OrderID) REFERENCES Orders(OrderID) ON DELETE CASCADE,
    CONSTRAINT fk_orderdetails_product
        FOREIGN KEY (ProductID) REFERENCES Products(ProductID)
);
""")

conn.commit()
print("Tables created successfully.")

Tables created successfully.

This script creates all four tables from the Excel file and applies the constraints exactly as described:

* PRIMARY KEY for unique row identification
* AUTO_INCREMENT for automatic IDs
* NOT NULL to prevent missing required values
* UNIQUE on customer email
* CHECK constraints for phone, price, stock, quantity, subtotal, and total amount
* FOREIGN KEY constraints to enforce relationships between tables
* ON DELETE CASCADE on OrderDetails.OrderID so deleting an order also removes its details

2. SQL Transaction to Handle an Order Purchase

In [18]:
import sqlite3

# Assuming 'conn' is already established (from previous cells)
# If not, you would need to establish it, e.g., conn = sqlite3.connect('ordermanagement_assignment3.db')

def process_order_transaction(customer_id, product_id, quantity):
    try:
        # Start a transaction (sqlite3 handles this implicitly with commit/rollback
        # but an explicit BEGIN can be used for clarity if needed)
        conn.execute("BEGIN TRANSACTION;")

        # Step 1: Check stock and get product price
        # Using a single SELECT statement to get both price and stock
        cursor = conn.execute(
            "SELECT Price, StockQuantity FROM Products WHERE ProductID = ?;",
            (product_id,)
        )
        result = cursor.fetchone()

        if result is None:
            print(f"Product with ID {product_id} not found.")
            conn.rollback()
            return

        product_price, available_stock = result

        # Step 2: Check if stock is sufficient
        if available_stock < quantity:
            print(f"Insufficient stock for Product ID {product_id}. Available: {available_stock}, Requested: {quantity}")
            conn.rollback()
            return

        # Step 3: Calculate total amount
        total_amount = product_price * quantity

        # Step 4: Insert into Orders table
        cursor = conn.execute(
            "INSERT INTO Orders (CustomerID, OrderDate, TotalAmount) VALUES (?, DATE('now'), ?);",
            (customer_id, total_amount)
        )
        order_id = cursor.lastrowid # Get the generated OrderID

        # Step 5: Insert into OrderDetails table
        conn.execute(
            "INSERT INTO OrderDetails (OrderID, ProductID, Quantity, Subtotal) VALUES (?, ?, ?, ?);",
            (order_id, product_id, quantity, total_amount)
        )

        # Step 6: Reduce stock in Products table
        conn.execute(
            "UPDATE Products SET StockQuantity = StockQuantity - ? WHERE ProductID = ?;",
            (quantity, product_id)
        )

        # If all steps succeed, commit the transaction
        conn.commit()
        print(f"Order {order_id} processed successfully for Customer {customer_id}, Product {product_id}, Quantity {quantity}.")

    except sqlite3.Error as e:
        print(f"An SQLite error occurred: {e}")
        conn.rollback()
    except Exception as e:
        print(f"An unexpected error occurred: {e}")
        conn.rollback()

# --- Example Usage --- #
# First, let's ensure some dummy data exists for customers and products
# (You might want to run this in a separate setup cell or just ensure your previous setup created these)

# Clear existing data for a fresh run, if desired
# conn.execute("DELETE FROM OrderDetails;")
# conn.execute("DELETE FROM Orders;")
# conn.execute("DELETE FROM Products;")
# conn.execute("DELETE FROM Customers;")

# Add some sample customers
conn.execute("INSERT OR IGNORE INTO Customers (CustomerID, FirstName, LastName, Email, Phone) VALUES (?, ?, ?, ?, ?);", (1, 'Alice', 'Smith', 'alice@example.com', '1112223333'))
conn.execute("INSERT OR IGNORE INTO Customers (CustomerID, FirstName, LastName, Email, Phone) VALUES (?, ?, ?, ?, ?);", (2, 'Bob', 'Johnson', 'bob@example.com', '4445556666'))

# Add some sample products with initial stock
conn.execute("INSERT OR IGNORE INTO Products (ProductID, ProductName, Price, StockQuantity) VALUES (?, ?, ?, ?);", (101, 'Laptop', 1200.00, 10))
conn.execute("INSERT OR IGNORE INTO Products (ProductID, ProductName, Price, StockQuantity) VALUES (?, ?, ?, ?);", (102, 'Mouse', 25.00, 50))
conn.execute("INSERT OR IGNORE INTO Products (ProductID, ProductName, Price, StockQuantity) VALUES (?, ?, ?, ?);", (103, 'Keyboard', 75.00, 20))
conn.commit()

print("--- Initial Product Stock ---")
cursor = conn.execute("SELECT ProductID, ProductName, StockQuantity FROM Products;")
for row in cursor.fetchall():
    print(f"Product ID: {row[0]}, Name: {row[1]}, Stock: {row[2]}")

# Test Case 1: Successful purchase
print("\n--- Test Case 1: Successful purchase ---")
process_order_transaction(customer_id=1, product_id=101, quantity=2)

# Test Case 2: Insufficient stock
print("\n--- Test Case 2: Insufficient stock ---")
process_order_transaction(customer_id=2, product_id=101, quantity=15) # Should fail as only 8 remain (10 - 2)

# Test Case 3: Another successful purchase
print("\n--- Test Case 3: Another successful purchase ---")
process_order_transaction(customer_id=1, product_id=102, quantity=10)

print("\n--- Final Product Stock ---")
cursor = conn.execute("SELECT ProductID, ProductName, StockQuantity FROM Products;")
for row in cursor.fetchall():
    print(f"Product ID: {row[0]}, Name: {row[1]}, Stock: {row[2]}")

print("\n--- Orders ---")
cursor = conn.execute("SELECT OrderID, CustomerID, OrderDate, TotalAmount FROM Orders;")
for row in cursor.fetchall():
    print(f"Order ID: {row[0]}, Customer ID: {row[1]}, Date: {row[2]}, Total: {row[3]}")

print("\n--- Order Details ---")
cursor = conn.execute("SELECT OrderDetailID, OrderID, ProductID, Quantity, Subtotal FROM OrderDetails;")
for row in cursor.fetchall():
    print(f"Detail ID: {row[0]}, Order ID: {row[1]}, Product ID: {row[2]}, Quantity: {row[3]}, Subtotal: {row[4]}")

--- Initial Product Stock ---
Product ID: 101, Name: Laptop, Stock: 10
Product ID: 102, Name: Mouse, Stock: 50
Product ID: 103, Name: Keyboard, Stock: 20

--- Test Case 1: Successful purchase ---
Order 1 processed successfully for Customer 1, Product 101, Quantity 2.

--- Test Case 2: Insufficient stock ---
Insufficient stock for Product ID 101. Available: 8, Requested: 15

--- Test Case 3: Another successful purchase ---
Order 2 processed successfully for Customer 1, Product 102, Quantity 10.

--- Final Product Stock ---
Product ID: 101, Name: Laptop, Stock: 8
Product ID: 102, Name: Mouse, Stock: 40
Product ID: 103, Name: Keyboard, Stock: 20

--- Orders ---
Order ID: 1, Customer ID: 1, Date: 2026-05-08, Total: 2400
Order ID: 2, Customer ID: 1, Date: 2026-05-08, Total: 250

--- Order Details ---
Detail ID: 1, Order ID: 1, Product ID: 101, Quantity: 2, Subtotal: 2400
Detail ID: 2, Order ID: 2, Product ID: 102, Quantity: 10, Subtotal: 250

This transaction ensures the order process is atomic. That means all steps succeed together or none of them happen.

The transaction does the following:

checks the available stock,
creates a new order,
inserts the order details,
updates product stock,
commits the transaction if everything is valid.
If the requested quantity is greater than the available stock, the transaction performs a ROLLBACK, which cancels all changes and prevents an invalid sale.

3. Partition the Orders Table Using RANGE Partitioning

In [20]:
conn.execute("DROP TABLE IF EXISTS Orders_Partitioned;")

conn.execute("""
CREATE TABLE Orders_Partitioned (
    OrderID INTEGER PRIMARY KEY AUTOINCREMENT,
    CustomerID INT,
    OrderDate DATE NOT NULL,
    TotalAmount DECIMAL(10,2),
    CONSTRAINT chk_totalamount_partitioned
        CHECK (TotalAmount > 0),
    CONSTRAINT fk_orders_partitioned_customer
        FOREIGN KEY (CustomerID) REFERENCES Customers(CustomerID)
);
""")
conn.commit()
print("Orders_Partitioned table created successfully (without partitioning as it's not supported in SQLite).")

Orders_Partitioned table created successfully (without partitioning as it's not supported in SQLite).

This partitions the Orders table into two sections:

p_before_2023 stores orders before 2023
p_2023_and_after stores orders from 2023 onward
This helps when querying date-based records because the database can scan only the relevant partition instead of the whole table.

For example, if you search for orders placed in 2024, the database can focus only on the 2023_and_after partition

### 4. How Indexing Improved Query Performance
Indexes improve query performance by making data retrieval faster. Without an index, the database may need to scan every row in a table to find matching records. This is called a full table scan, and it becomes slow when the table is large.

For this schema, indexing is especially useful on foreign key and date columns.

Example indexes:

In [22]:
conn.execute("CREATE INDEX idx_orders_customerid ON Orders(CustomerID);")
conn.execute("CREATE INDEX idx_orders_orderdate ON Orders(OrderDate);")
conn.execute("CREATE INDEX idx_orderdetails_orderid ON OrderDetails(OrderID);")
conn.execute("CREATE INDEX idx_orderdetails_productid ON OrderDetails(ProductID);")
conn.commit()
print("Indexes created successfully.")

Indexes created successfully.

These indexes improve performance in several ways.

An index on Orders(CustomerID) helps when searching for all orders made by a particular customer.

An index on Orders(OrderDate) helps for date filtering, sorting, and partition-related queries.

Indexes on OrderDetails(OrderID) and OrderDetails(ProductID) improve joins between Orders, OrderDetails, and Products.

For example, this query becomes faster with indexes:

In [25]:
query = """
SELECT o.OrderID, o.OrderDate, od.ProductID, od.Quantity
FROM Orders o
JOIN OrderDetails od ON o.OrderID = od.OrderID
WHERE o.CustomerID = 1;
"""

df_result = pd.read_sql(query, conn)
display(df_result)

   OrderID   OrderDate  ProductID  Quantity
0        1  2026-05-08        101         2
1        2  2026-05-08        102        10

Instead of checking all rows in both tables, the database can use the index to quickly locate the needed records.

At the same time, indexing has a tradeoff. It improves SELECT performance, but it can slightly slow down INSERT, UPDATE, and DELETE operations because the indexes must also be updated whenever data changes

### Conclusion
The Excel file provided the schema for four related tables in an order management system: `Customers`, `Products`, `Orders`, and `OrderDetails`.

The SQL script created these tables with the appropriate constraints to maintain data integrity. The transaction logic ensured that an order purchase is only completed when enough stock is available, otherwise the transaction is rolled back. The Orders table was partitioned by OrderDate using RANGE partitioning so that older and newer records are stored separately for better management and performance. Finally, indexing improved query efficiency by speeding up searches, joins, and date-based filtering.